"""hook: SessionStart の通知（AC4b・AC17・AC18）と PreToolUse の誘導・自動許可（AC19〜AC22）。"""
import json
import shutil
from pathlib import Path

import pytest

from serena_lsp_testlib import PLUGIN, files_of, make_repo, run_cli
from serena_lsp import hooks

PY_PLUGIN = "pyright-lsp@claude-plugins-official"


# ---- SessionStart ------------------------------------------------------------

def _yml(root, languages, excluded=None):
    (root / ".serena").mkdir(exist_ok=True)
    body = "language_servers:\n" + "".join(f"- {l}\n" for l in languages) if languages else "language_servers: []\n"
    if excluded is not None:
        body += "mcp_serena_excluded:\n" + "".join(f"- {e}\n" for e in excluded) if excluded else "mcp_serena_excluded: []\n"
    (root / ".serena/project.yml").write_text("project_name: x\n" + body)


def _env(tmp_path, plugins=(PY_PLUGIN,), binaries=("pyright-langserver", "shellcheck"), plugin_root=True):
    home = tmp_path / "home"
    (home / ".claude/plugins").mkdir(parents=True, exist_ok=True)
    (home / ".claude/plugins/installed_plugins.json").write_text(
        json.dumps({"version": 2, "plugins": {p: [] for p in plugins}}))
    bindir = tmp_path / "bin"
    bindir.mkdir(exist_ok=True)
    (bindir / "git").symlink_to(shutil.which("git"))
    for b in binaries:
        (bindir / b).write_text("#!/bin/sh\n")
        (bindir / b).chmod(0o755)
    env = {"HOME": str(home), "PATH": str(bindir), "XDG_STATE_HOME": str(tmp_path / "state")}
    if plugin_root:
        env["CLAUDE_PLUGIN_ROOT"] = str(PLUGIN)
    return env


def _session_start(root, env, client="claude-code"):
    import os
    full = {k: v for k, v in os.environ.items() if k != "CLAUDE_PLUGIN_ROOT"}
    full.update(env)
    import subprocess, sys
    from serena_lsp_testlib import CLI
    proc = subprocess.run([sys.executable, str(CLI), "hook", "session-start", "--client", client],
                          input=json.dumps({"cwd": str(root), "session_id": "s"}), capture_output=True,
                          text=True, env=full)
    assert proc.returncode == 0
    if not proc.stdout.strip():
        return ""
    out = json.loads(proc.stdout)["hookSpecificOutput"]
    assert out["hookEventName"] == "SessionStart"
    return out["additionalContext"]


@pytest.fixture
def pyrepo(tmp_path):
    return make_repo(tmp_path / "r", files_of(py=30))


@pytest.fixture
def mixed(tmp_path):
    return make_repo(tmp_path / "r", files_of(py=30, sh=12, php=3))


def test_mismatch_is_reported(tmp_path, mixed):
    _yml(mixed, ["python"], [])
    text = _session_start(mixed, _env(tmp_path))
    assert "bash" in text and "12" in text
    assert "/mcp-serena:language-servers" in text
    assert "php" not in text  # しきい値未満は知らせない


def test_missing_install_is_reported(tmp_path, pyrepo):
    _yml(pyrepo, ["python"], [])
    text = _session_start(pyrepo, _env(tmp_path, plugins=()))
    assert "pyright-lsp" in text


def test_all_present_prints_nothing(tmp_path, pyrepo):
    _yml(pyrepo, ["python"], [])
    assert _session_start(pyrepo, _env(tmp_path)) == ""


def test_unconfigured_repo_gets_only_the_unconfigured_notice(tmp_path, pyrepo):
    text = _session_start(pyrepo, _env(tmp_path, plugins=()))
    assert "/mcp-serena:language-servers" in text
    assert "pyright-lsp" not in text  # 欠けの行は出さない
    assert len(text.splitlines()) == 2


def test_autogenerated_yml_without_mark_is_unconfigured(tmp_path, mixed):
    _yml(mixed, ["python"])  # 目印が無い
    text = _session_start(mixed, _env(tmp_path, plugins=()))
    assert len(text.splitlines()) == 2
    assert "pyright-lsp" not in text


def test_repo_without_languages_prints_nothing(tmp_path):
    repo = make_repo(tmp_path / "r", {"README.md": "x"})
    assert _session_start(repo, _env(tmp_path)) == ""


def test_non_git_directory_prints_nothing(tmp_path):
    # 採る言語のファイルがあっても、git のリポジトリでなければ未設定の通知も出さない（AC18）。
    plain = tmp_path / "plain"
    for rel, body in files_of(py=30).items():
        (plain / rel).parent.mkdir(parents=True, exist_ok=True)
        (plain / rel).write_text(body)
    assert _session_start(plain, _env(tmp_path)) == ""


@pytest.mark.parametrize("excluded", [["bash health_check_exit_1"], ["bash not_selected"]])
def test_excluded_languages_are_not_mismatches(tmp_path, excluded):
    repo = make_repo(tmp_path / "r", files_of(py=30, sh=12))
    _yml(repo, ["python"], excluded)
    assert _session_start(repo, _env(tmp_path)) == ""


def test_named_language_below_threshold_is_not_reported(tmp_path, pyrepo):
    _yml(pyrepo, ["python", "bash"], [])
    assert _session_start(pyrepo, _env(tmp_path)) == ""


def test_local_override_with_excluded_in_project_yml(tmp_path):
    repo = make_repo(tmp_path / "r", files_of(py=30, sh=12))
    _yml(repo, ["bash"], ["bash health_check_exit_1"])
    (repo / ".serena/project.local.yml").write_text("language_servers:\n- python\n")
    assert _session_start(repo, _env(tmp_path)) == ""


def test_codex_does_not_report_claude_code_lsp(tmp_path, pyrepo):
    _yml(pyrepo, ["python"], [])
    env = _env(tmp_path, plugins=(), binaries=(), plugin_root=False)
    assert _session_start(pyrepo, env, client="codex") == ""


def test_claude_code_client_without_plugin_root_prints_nothing(tmp_path, mixed):
    _yml(mixed, ["python"], [])
    assert _session_start(mixed, _env(tmp_path, plugin_root=False)) == ""


def test_extra_check_missing_is_reported_without_item_label(tmp_path):
    # 現状固定: shellcheck は ITEM_LABELS に無いため else 分岐が「診断に要るもの」の行を出す。
    repo = make_repo(tmp_path / "r", files_of(sh=12))
    _yml(repo, ["bash"], [])
    text = _session_start(repo, _env(tmp_path, plugins=(), binaries=("pyright-langserver",)))
    assert "bash" in text and "shellcheck" in text
    assert "/mcp-serena:language-servers" in text


def test_broken_installed_plugins_swallows_missing_check(tmp_path, mixed):
    # 現状固定: installed_plugins.json が壊れていると check.Unreadable を握りつぶし、
    #          食い違いの行は出るが欠けの行は出ない。
    _yml(mixed, ["python"], [])
    env = _env(tmp_path)
    broken = Path(env["HOME"]) / ".claude/plugins/installed_plugins.json"
    broken.write_text("{ not json")
    text = _session_start(mixed, env)
    assert "bash" in text and "12" in text  # 食い違いの行は出る
    assert "pyright-lsp" not in text  # 欠けの行は出ない
    assert "診断に要るもの" not in text


def test_unsupported_project_yml_shape_prints_nothing(tmp_path, pyrepo):
    # 現状固定: language_servers が流れの形（[python]）だと py.UnsupportedShape で何も出さない。
    (pyrepo / ".serena").mkdir(exist_ok=True)
    (pyrepo / ".serena/project.yml").write_text("project_name: x\nlanguage_servers: [python]\n")
    assert _session_start(pyrepo, _env(tmp_path)) == ""


# ---- PreToolUse -------------------------------------------------------------

SERENA = "mcp__plugin_mcp-serena_serena__"


@pytest.fixture
def configured(tmp_path, monkeypatch):
    root = tmp_path / "r"
    root.mkdir()
    _yml(root, ["python"], [])
    monkeypatch.setenv("CLAUDE_PLUGIN_ROOT", str(PLUGIN))
    monkeypatch.setenv("XDG_STATE_HOME", str(tmp_path / "state"))
    clock = {"now": 1_000_000.0}
    monkeypatch.setattr(hooks, "_now", lambda: clock["now"])
    return {"root": root, "clock": clock}


def _call(ctx, tool, tool_input=None, client="claude-code", mode="default", session="s1"):
    ctx["clock"]["now"] += 1
    payload = {"session_id": session, "tool_name": tool, "tool_input": tool_input or {},
               "permission_mode": mode, "cwd": str(ctx["root"])}
    out = (hooks.pre_tool_use(payload, client) or {}).get("hookSpecificOutput", {})
    if "additionalContext" in out:
        assert "permissionDecision" not in out  # 案内は実行を止めない
        return "notice"
    return out.get("permissionDecision")


def _read(ctx, path, **kw):
    return _call(ctx, "Read", {"file_path": str(ctx["root"] / path)}, **kw)


@pytest.mark.parametrize("path,noticed", [("a.md", False), ("a.json", False), ("a.py", True), ("a.ts", False)])
def test_only_adopted_language_files_count(configured, path, noticed):
    decisions = [_read(configured, path) for _ in range(3)]
    assert decisions == [None, None, "notice" if noticed else None]


def test_grep_three_times_notices_and_resets(configured):
    assert [_call(configured, "Grep", {"pattern": "x"}) for _ in range(3)] == [None, None, "notice"]


def test_mixed_four_notices(configured):
    ctx = configured
    seq = [_call(ctx, "Grep"), _read(ctx, "a.py"), _call(ctx, "Grep"), _read(ctx, "a.py")]
    assert seq == [None, None, None, "notice"]


def test_bash_grep_and_read_are_counted(configured):
    ctx = configured
    seq = [_call(ctx, "Bash", {"command": "sed -n 1,80p a.py"}) for _ in range(3)]
    assert seq == [None, None, "notice"]


def test_no_notice_within_120_seconds_and_counts_again_after(configured):
    ctx = configured
    for _ in range(3):
        _read(ctx, "a.py")
    base = ctx["clock"]["now"]
    ctx["clock"]["now"] = base + 115
    assert [_read(ctx, "a.py") for _ in range(3)] == [None, None, None]  # 116〜118 秒: 数えない
    ctx["clock"]["now"] = base + 119
    assert [_read(ctx, "a.py") for _ in range(3)] == [None, None, "notice"]  # 120 秒から数える


def test_count_expires_after_1000_seconds(configured):
    ctx = configured
    _read(ctx, "a.py")
    _read(ctx, "a.py")
    ctx["clock"]["now"] += 1001
    assert _read(ctx, "a.py") is None


def test_symbolic_serena_tool_resets_but_search_and_diagnostics_do_not(configured):
    ctx = configured
    _read(ctx, "a.py"); _read(ctx, "a.py")
    _call(ctx, SERENA + "find_symbol")
    assert _read(ctx, "a.py") is None
    _read(ctx, "a.py")
    _call(ctx, SERENA + "get_diagnostics_for_file")
    assert _read(ctx, "a.py") == "notice"


def test_search_for_pattern_counts_as_grep(configured):
    ctx = configured
    assert [_call(ctx, SERENA + "search_for_pattern") for _ in range(3)] == [None, None, "notice"]


def test_parallel_calls_do_not_lose_counts(configured, monkeypatch):
    # 読みと書きの間を広げても、同じセッションの並列の呼び出しは直列になり、増分を失わない。
    import threading, time as _time
    load = hooks._load_counts
    monkeypatch.setattr(hooks, "_load_counts", lambda path: (_time.sleep(0.2), load(path))[1])
    threads = [threading.Thread(target=_read, args=(configured, "a.py")) for _ in range(2)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert load(hooks._state_path("s1"))["read"] == 2


def test_unmarked_repo_counts_nothing(configured):
    (configured["root"] / ".serena/project.yml").write_text("language_servers:\n- python\n")
    assert [_read(configured, "a.py") for _ in range(4)] == [None] * 4


def test_notice_names_symbol_tools_without_blocking(configured):
    ctx = configured
    for _ in range(2):
        _read(ctx, "a.py")
    ctx["clock"]["now"] += 1
    out = hooks.pre_tool_use({"session_id": "s1", "tool_name": "Read", "tool_input": {"file_path": "a.py"},
                              "cwd": str(ctx["root"])}, "claude-code")
    assert "permissionDecision" not in out["hookSpecificOutput"]
    reason = out["hookSpecificOutput"]["additionalContext"]
    assert len(reason.splitlines()) <= 3
    for tool in ("get_symbols_overview", "find_symbol", "find_referencing_symbols", "replace_symbol_body"):
        assert tool in reason


@pytest.mark.parametrize("mode,expected", [("acceptEdits", "allow"), ("auto", "allow"),
                                           ("default", None), ("bypassPermissions", None)])
def test_auto_allow_serena_tools(configured, mode, expected):
    assert _call(configured, SERENA + "find_symbol", mode=mode) == expected


def test_codex_never_allows_and_reads_shell_commands(configured):
    ctx = configured
    assert _call(ctx, "mcp__serena__find_symbol", client="codex", mode="acceptEdits") is None
    seq = [_call(ctx, "Bash", {"command": "sed -n 1,80p a.py"}, client="codex") for _ in range(3)]
    assert seq == [None, None, "notice"]


def test_codex_list_command_is_unwrapped(configured):
    ctx = configured
    cmd = ["bash", "-lc", "cat src/a.py"]
    assert [_call(ctx, "shell", {"command": cmd}, client="codex") for _ in range(3)] == [None, None, "notice"]


def test_codex_hook_definition_matches_shell_tools():
    data = json.loads((PLUGIN / "hooks/codex.json").read_text())
    import re
    matcher = data["hooks"]["PreToolUse"][0]["matcher"]
    for name in ("Bash", "shell", "exec_command", "local_shell", "mcp__serena__find_symbol"):
        assert re.fullmatch(matcher, name), name
    for event in ("PreToolUse", "SessionStart"):
        command = data["hooks"][event][0]["hooks"][0]["command"]
        assert "--client codex" in command


def test_broken_input_prints_nothing(tmp_path):
    for stdin in ("", "not json", "[]", '{"cwd": 1}'):
        proc = run_cli("hook", "pre-tool-use", "--client", "claude-code", stdin=stdin,
                       env={"CLAUDE_PLUGIN_ROOT": str(PLUGIN)})
        assert (proc.returncode, proc.stdout) == (0, "")
